name: Build and Test

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]
  workflow_dispatch: 
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: dotnet build --configuration Debug src/Zip2City/Zip2City/Zip2City.csproj
    - name: Test
      run: dotnet test --verbosity detailed src/Zip2City/Zip2CityTests/Zip2CityTests.csproj 
